name: terhal_app
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any

  cupertino_icons: ^1.0.2
  get: ^4.6.6
  http: ^1.1.0
  firebase_core: ^2.22.0
  google_sign_in: ^6.1.6
  google_fonts: ^6.1.0
  shared_preferences: ^2.2.1
  connectivity_plus: ^5.0.1
  flutter_form_builder: ^9.1.1
  form_builder_validators: ^9.1.0
  flutter_spinkit: ^5.2.0
  flutter_native_splash: ^2.3.2
  firebase_auth: ^4.13.0
  cloud_firestore: ^4.13.0
  rflutter_alert: ^2.0.7
  google_maps_flutter: ^2.5.0
  geolocator: ^10.1.0
  badges: ^3.1.2
  flutter_staggered_animations: ^1.1.1
  cached_network_image: ^3.3.0
  logging: ^1.2.0
  weather: ^3.1.1
  permission_handler: ^11.0.1
  crypto: ^3.0.3
  flutter_polyline_points: ^2.0.0
  json_annotation: ^4.8.1
  flutter_rating_bar: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.1

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
    - assets/json/
